#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           LiMon
# Required-Start:     $docker
# Required-Stop:      $docker
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  LiMoning Center based on docker image with Graphite, ElasticSearch anf Grafana
# Description:
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

conf=/etc/LiMon/docker-compose.yml

case "$1" in
	start)
		[ -f $conf ] && docker-compose -f $conf -p LiMon up -d --force-recreate
		;;

	stop)
		[ -f $conf ] && docker-compose -f $conf -p LiMon stop	
		;;

	restart)
		[ -f $conf ] && docker-compose -f $conf -p LiMon up -d --force-recreate
		;;

	logs)
		[ -f $conf ] && docker-compose -f $conf -p LiMon logs
		;;

	check)
		
		[ -f $conf ] && docker-compose -f $conf -p LiMon ps
		;;
	
	recreate)
                [ -f $conf ] && docker-compose -f $conf -p LiMon up -d --force-recreate
		;;

        upgrade)
                if [ -f $conf ] ; then
                        [ -f $conf ] && docker-compose -f $conf -p LiMon pull
                        echo
                        echo "if one image was updated, please run \"$0 recreate\""
                        echo
                fi
                ;;

	*)
		echo "Usage: $0 {start|stop|restart|status|check|logs|upgrade}"
		exit 1
		;;
esac
