#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           monitor
# Required-Start:     $docker
# Required-Stop:      $docker
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Monitoring docker-build infra with Graphite, ElasticSearch anf Grafana
# Description:
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

figconf=/etc/monitor/fig.yml

case "$1" in
	start)
		[ -f $figconf ] && fig -f $figconf -p monitor start
		;;

	stop)
		[ -f $figconf ] && fig -f $figconf -p monitor stop	
		;;

	restart)
		[ -f $figconf ] && fig -f $figconf -p monitor restart
		;;

	logs)
		[ -f $figconf ] && fig -f $figconf -p monitor logs
		;;

	status)
		
		[ -f $figconf ] && fig -f $figconf -p monitor ps
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status|logs}"
		exit 1
		;;
esac
